### ISSUE TITLE
Капча

### ISSUE THREAD

**Issue by catamphetamine** [mishamoix/Channy#5]
Здравствуйте.
Вы как-то решили вопрос капчи?
У самого Двача никакой документации на это нету.
У вас есть, возможно, какие-то свои записи?
В стиле: "отправить то-то на такой-то URL, и потом делать то-то".

**Comment by catamphetamine** [comment]
Ага, вижу, вы подменяете origin у WebView как-то, подсовываете `baseURL` нужного сайта (2ch, 4chan, ...) этому WebView, и там уже это всё делаете в скрипте.

https://github.com/mishamoix/Channy/blob/c59eddaca3c953bf8f7bac80be695e66152cbbda/Chan/Sources/Modules/Write/Captcha/Recaptcha/RecaptchaViewController.swift

```swift
        if let wk = wk {
            wk.loadHTMLString("<body></body>", baseURL: URL(string: self.host!)!)
        }
```

https://github.com/mishamoix/Channy/blob/c59eddaca3c953bf8f7bac80be695e66152cbbda/Chan/Resources/recaptchaScript.js

```js
            grecaptcha.render(el, {
                                    'sitekey': RECAPTCHA_SITE_KEY,
                                    'callback': captchaSolved,
                                    'expired-callback': captchaExpired,
                                    });
```

И без `baseUrl` это всё дело не работало бы, потому что открытый ключ работает только на определённом домене.

Это, я так понимаю, обычная РеКапча, где галку нажимают.
А что насчёт "invisible recaptcha"? 
https://github.com/mishamoix/Channy/blob/c59eddaca3c953bf8f7bac80be695e66152cbbda/Chan/Sources/Modules/Write/Captcha/Recaptcha/InvisibleRecaptchaViewController.swift
Вы её как-то сумели сделать? Или она в принципе не работает в мобильных приложениях?

**Comment by chebyrash** [comment]
Привет, мы сделали на сервере

https://github.com/chebyrash/one/blob/fccdf5a21c9e9f5cbebb7751304014dd02cf7605/src/main/scala/engine/imageboards/dvach/Dvach.scala#L290

**Comment by catamphetamine** [comment]
@chebyrash Ага, тоже как-то подсовываете `g-captcha-response`, а где берёте его?
Вижу, что используете открытый ключ Двача для показа капчи, но капча же вроде бы работает только на домене Двача?
То есть, если просто показать виджет РеКапчи с открытым ключом Двача на любом стороннем сайте, то такая капча не пройдёт при отправке поста? Как вы такое обошли?

**Comment by chebyrash** [comment]
В вебвьюхе на телефоне показываем челлендж и оттуда достаем решение g captcha response

**Comment by catamphetamine** [comment]
Ага, понятно, как все делают, в общем.
Стандартный подход, значит, такой.
Не для веба, потому что в вебе и фреймы не разрешают встраивать с других сайтов, и подменять origin у них для рекапчи.
Ок, спс.

**Comment by chebyrash** [comment]
@catamphetamine читал про тебя недавно на хн, имхо на будущее не стоит винить "большие корпорации" и просто не оскорблять людей в тырнете )

**Comment by catamphetamine** [comment]
@chebyrash Очень многие люди, похоже, не услышали того, что я говорил. Я не удивлён. Мне, конечно же, без разницы, а свой выбор я сделал, и позицию выразил.

**Comment by chebyrash** [comment]
@catamphetamine
Only that I’m more used to GitHub so I’ve posted a (now deleted) issue rather than a tweet. The issue was titled “You’re a [funny-word]” where [funny-word] was a set of latin characters resembling a transliterated Russian half-offensive word for “g*y” which also has a very broad meaning and is most commonly used as an “assh*le” rather than “g*y”.

Ну типа камон, всё-таки ты просто пытался оправдаться
В нормис пространстве общаться это не на дваче капчевать

**Comment by catamphetamine** [comment]
@chebyrash Это не было оправданием. Я ни перед кем не оправдываюсь. Оправдываться должны те, кто забанил все мои репозитории за странное русское слово. Им без разницы, потому что они тоже дпиары.

Все, кто не согласен с моей позицией, также дпиары. Дпиары, не видящие и не зрячие.

**Comment by catamphetamine** [comment]
(забанил вас для профилактики)
